config/routes.rb
Rails.application.routes.draw do




  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'tutorial/index'
  get 'contact/index'
  get 'presentation/index'
  get 'welcome/index'

  resources :teams do
  	resources :okrs do
  		resources :krs
  	end
  end


root 'welcome#index'


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kr.rb
class Kr < ApplicationRecord
  belongs_to :okr
end

app/models/okr.rb
class Okr < ApplicationRecord
  belongs_to :team
  has_many :krs, dependent: :destroy
end

app/models/team.rb
class Team < ApplicationRecord
    belongs_to :user
    has_many :okrs, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :teams
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name])
  end
  
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  
end

app/controllers/krs_controller.rb
class KrsController < ApplicationController
  before_action :set_team
  before_action :set_okr
  before_action :set_kr, only: [:show, :edit, :update, :destroy]

  # GET /krs
  # GET /krs.json
  def index
    @krs = Kr.all
  end

  # GET /krs/1
  # GET /krs/1.json
  def show
  end

  # GET /krs/new
  def new
    @team = Team.find(params[:team_id])
    @okr = Okr.find(params[:okr_id])
    @kr = Kr.new
  end

  # GET /krs/1/edit
  def edit
    @okr = Okr.find(params[:okr_id])
  end

  # POST /krs
  # POST /krs.json
  def create
    @team = Team.find(params[:team_id])
    @okr = Okr.find(params[:okr_id])
    @kr = Kr.new(kr_params)


      if @kr.save
        redirect_to action: "show", id: @kr.id


        #format.html { redirect_to @kr, notice: 'Kr was successfully created.' }
        #format.json { render :show, status: :created, location: @kr }
      else
        flash[:error] = @kr.error.full_messages
        redirect_to action: "new", id: @kr.id


        #format.html { render :new }
        #format.json { render json: @kr.errors, status: :unprocessable_entity }

      end
  end

  # PATCH/PUT /krs/1
  # PATCH/PUT /krs/1.json
  def update

    if @kr.update(kr_params)

          redirect_to action: "show", id: @kr.id, notice: "O KR foi editado com sucesso!"
     else


    end
  end

  # DELETE /krs/1
  # DELETE /krs/1.json
  def destroy
    @kr.destroy
    redirect_to team_okr_krs_path(@okr)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:team_id])
    end

    def set_okr
      @okr = Okr.find(params[:okr_id])
    end

    def set_kr
      @kr = Kr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kr_params
      params.require(:kr).permit(:title, :howtoscore, :progress, :okr_id)
    end
end

app/controllers/okrs_controller.rb
class OkrsController < ApplicationController
  before_action :set_team
  before_action :set_okr, only: [:show, :edit, :update, :destroy]

  # GET /okrs
  # GET /okrs.json
  def index
    @okrs = Okr.all

  end

  # GET /okrs/1
  # GET /okrs/1.json
  def show

  end

  # GET /okrs/new
  def new
    @team = Team.find(params[:team_id])
    @okr = Okr.new
  end

  # GET /okrs/1/edit
  def edit
    @team = Team.find(params[:team_id])
  end

  # POST /okrs
  # POST /okrs.json
  def create
    @team = Team.find(params[:team_id])
    @okr = Okr.new(okr_params)

      if @okr.save
          #flash[:sucess] = "Sucesso!"
          redirect_to action: "show", id: @okr.id
        #format.html { redirect_to @okr, notice: 'Okr was successfully created.' }
        #format.json { render :show, status: :created, location: @okr }
      else
        flash[:error] = @okr.error.full_messages
        redirect_to action: "new", id: @okr.id

        #format.html { render :new }
        #format.json { render json: @okr.errors, status: :unprocessable_entity }
      end

  end

  # PATCH/PUT /okrs/1
  # PATCH/PUT /okrs/1.json
  def update

      if @okr.update(okr_params)

          redirect_to action: "show", id: @okr.id, notice: "A Okr foi editado com sucesso!"
        #format.html { redirect_to @okr, notice: 'Okr was successfully updated.' }
        #format.json { render :show, status: :ok, location: @okr }
      else

        #format.html { render :edit }
        #format.json { render json: @okr.errors, status: :unprocessable_entity }

      end
  end

  # DELETE /okrs/1
  # DELETE /okrs/1.json
  def destroy

    @okr.destroy
    redirect_to team_okrs_path(@team)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:team_id])
    end



    def set_okr
      @okr = Okr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def okr_params
      params.require(:okr).permit(:title, :description, :progress, :team_id)
    end
end

app/controllers/presentation_controller.rb
class PresentationController < ApplicationController
  def index
  end
  
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Equipe criada com sucesso!' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Equipe atualizada com sucesso!' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Equipe deletada com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:title, :description)
    end
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def progresso_okr (okr)
            @okr = okr
            contagem = @okr.krs.count
            c = 0
            @okr.krs.each do |i|
                 c = c + i.progress
            end

            if contagem != 0
            progresso = c/contagem
            elsif contagem == 0
            progresso = 0
            end
            progresso
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/krs_helper.rb
module KrsHelper




end

app/helpers/presentation_helper.rb
module PresentationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<style>
div.pad {
    padding: 25px;
}

</style>


<h1>Fale com nosso time</h1>

<br>
<div align="center">
<h1 style="font-family: 'courier' ">
	<strong>
	Desenvolvedores
	</strong>
</h1>	
           <div class="pad">
            <img alt="Arthur Farias" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/13900376_1053728778047268_6370108279326510345_n.jpg?oh=552e44bfe7c96a7139350fe025b133ed&oe=58891CC4" />
            <img alt="Caio Cavalcanti" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/13419056_651449448335410_6383356122176775996_n.jpg?oh=c0e4fe9598051d138ba5ee5d323919b2&oe=589B28E7" />
            <img alt="José Augusto" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/11998922_944143905608866_5223284539658861120_n.jpg?oh=9ee94a93899aae42138ad4ee972056c4&oe=58D2F7C6" />
            <img alt="Felipe Horácio" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/12728916_950010835075095_2062884892245245846_n.jpg?oh=360de36680103c13b0ac394a7dba230a&oe=5887F505" />
            </div>
</div>
<p> Celular:<em> 81 9 99658697</em></p>
<p>E-mail:<em> inkflow.ufpe@gmail.com</em></p>

app/views/contact/us.html.erb
<style>
div.pad {
    padding: 25px;
}

</style>


<h1>Fale com nosso time</h1>

<br>
<div align="center">
<h1 style="font-family: 'courier' ">
	<strong>
	Desenvolvedores
	</strong>
</h1>	
           <div class="pad">
            <img alt="Bootstrap Image Preview" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/13900376_1053728778047268_6370108279326510345_n.jpg?oh=552e44bfe7c96a7139350fe025b133ed&oe=58891CC4" />
            <img alt="Bootstrap Image Preview" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/13419056_651449448335410_6383356122176775996_n.jpg?oh=c0e4fe9598051d138ba5ee5d323919b2&oe=589B28E7" />
            <img alt="Bootstrap Image Preview" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/11998922_944143905608866_5223284539658861120_n.jpg?oh=9ee94a93899aae42138ad4ee972056c4&oe=58D2F7C6" />
            <img alt="Bootstrap Image Preview" src="https://scontent-gru2-1.xx.fbcdn.net/v/t1.0-1/p160x160/12728916_950010835075095_2062884892245245846_n.jpg?oh=360de36680103c13b0ac394a7dba230a&oe=5887F505" />
            </div>
</div>
<p> Celular:<em> 81 9 99658697</em></p>
<p>E-mail:<em> inkflow.ufpe@gmail.com</em></p>

app/views/krs/_form.html.erb
<%= form_for(kr) do |f| %>
  <% if kr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kr.errors.count, "error") %> prohibited this kr from being saved:</h2>

      <ul>
      <% kr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :howtoscore %>
    <%= f.text_area :howtoscore %>
  </div>

  <div class="field">
    <%= f.label :okr_id %>
    <%= f.text_field :okr_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/krs/edit.html.erb
<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item"><a href="/teams/<%=@team.id%>/okrs">Equipe: <em><%=@team.title%></em></a></li>
    <li class="breadcrumb-item"><a href="/teams/<%=@team.id%>/okrs/<%=@okr.id%>/krs">OKR: <em><%=@okr.title%></em></a></li>
    <li class="breadcrumb-item active"><strong>KR: <em><%=@kr.title%></em></strong></li>
  </ol>
</div>


<div align="center">
  <%if current_user.editor%>

  <h1>Editar KR</h1>

  <%= form_for ([@team, @okr, @kr]) do |f| %>

    <div class="field">
      <%= f.label :título %> <br>
      <%= f.text_field :title %>
    </div>

     <br>
    <div class="field">
      <%= f.label :howtoscore %> <br>
      <%= f.text_area :howtoscore, cols: "50", rows: "10" %>
    </div>
    <br>

    <div class="field">
      <%= f.label :progresso_do_KR, 'Progresso do KR' %> <br>
      <%= f.select :progress, ['0', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100'], {}, class:"btn btn-default dropdown-toggle" %>%
    </div>
    

    <div class="field">
      <%= f.hidden_field :okr_id%>
      <%= f.hidden_field :okr_id%>
    </div>

    <br>
    <div class="actions">
      <%= f.submit "Atualizar KR", class:"btn btn-primary"  %>
    </div>
  <% end %>


  <%= link_to 'Back', team_okr_krs_path %>
  <%else%>
  <h2>Você não está autorizado a acessar o conteúdo dessa página.</h2>
  <%= link_to 'Voltar', team_okr_krs_path %>
  <%end%>
</div>

app/views/krs/index.html.erb
<style>

th {
    text-align: center;
    background-color: purple;
    color: white;
    font-size: 20px;
}

td{
    background-color: white;
    text-align: center;
    font-size: 15px;
    color: black;
}
.percokr{
  width: 10%;
}
.nameokr{
  width: 20%;
}
.opcoesokr{
  width: 20%;
}

.progress {
  position: relative;

}
.progress span {
  position: absolute;
  display: block;
  width: 100%;
  color:purple;
}

</style>



<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item "><a href="/teams/<%=@team.id%>/okrs">Equipe: <em><%=@team.title%></em></a></li>
    <li class="breadcrumb-item active"><strong>OKR: <em><%=@okr.title%></em></strong></li>
  </ol>
</div>



<div class="row">
  <div class="col-md-12">
    <div class="col-md-5">
    </div>
      <div class="col-md-1" align="center">
        <h5>Criar KR</h5>
        <%= button_to new_team_okr_kr_path(@team, @okr), method: :get, class: "btn btn-primary", title:"Criar OKR" do %>
        <span class="glyphicon glyphicon-plus"></span>
        <%end%>
      </div>
      <div class="col-md-1" align="center">
        <h5>Voltar</h5>
        <%= button_to team_okrs_path, method: :get, class: "btn btn-info", title:"OKR" do %>
        <span class="glyphicon glyphicon-arrow-left"></span>
        <%end%>
      </div>
    <div class="col-md-5">
    </div>
  </div>
</div>
<br>

<div class="container-fluid">

<div class="progress" >
<div class="progress-bar progress-bar-striped active" role="progressbar"  style="width: <%= progresso_okr(@okr) %>%">
<strong><span> Progresso do OKR: <%= progresso_okr(@okr) %>%</span></strong>
</div>
</div>

  <div class="row">

    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>

            <th class="nameokr">
              KR
            </th>
            <th>
              How to score
            </th>
            <th class="percokr">
              Status
            </th>
            <th class="opcoesokr">
              Opções
            </th>

          </tr>

        </thead>
        <tbody>
          <% @okr.krs.each do |kr| %>
          <tr>
            <td>
              <strong><%= link_to kr.title, {:action => 'show', :id => kr.id} %></strong>
            </td>
            <td>
              <%= simple_format(kr.howtoscore) %>
            </td>
            <td>
                        <div class="progress" align="center" >
            <div class="progress-bar progress-bar-striped active" role="progressbar"  style="width: <%= kr.progress %>%">
            <strong><span><%= kr.progress %>%</span></strong>
            </div>
            </div>
            </td>
            <td>
              <%= link_to 'Mostrar', {:action => 'show', :id => kr.id}, class: "btn btn-default"%>
              <% if current_user.editor %>
              <%= link_to 'Editar', {:action => 'edit', :id => kr.id}, class: "btn btn-default" %>              
              <%= link_to 'Excluir', {:action => 'destroy', :id => kr.id}, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-default" %>
              <%end%>
            
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/krs/new.html.erb
<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item "><a href="/teams/<%=@team.id%>/okrs">Equipe: <em><%=@team.title%></em></a></li>
    <li class="breadcrumb-item active"><strong>OKR: <em><%=@okr.title%></em></strong></li>
  </ol>
</div>


<div align="center">

<% if current_user.editor%>
<h1>Novo KR</h1>

<%= form_for ([@team, @okr, @okr.krs.build]) do |f| %>

  <div class="field">
    <%= f.label :título %> <br>
    <%= f.text_field :title %>
  </div>
   <br>
  <div class="field">
    <%= f.label :howtoscore %> <br>
    <%= f.text_area :howtoscore, cols: "50", rows: "10" %>
  </div>
  <br>

   <div class="field">
    <%= f.label :progresso_do_KR, 'Progresso do KR' %> <br>
    <%= f.select :progress, ['0', '10', '20', '30', '40', '50', '60', '70', '80', '90', '100'], {}, class:"btn btn-default dropdown-toggle" %>%
  </div>


  <div class="field">
    <%= f.hidden_field :okr_id %>
    <%= f.hidden_field :okr_id %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit "Criar KR", class:"btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Voltar', team_okr_krs_path %>
<%else%>
<h2>Você não está autorizado a acessar o conteúdo dessa página.</h2>
<%= link_to 'Voltar', team_okr_krs_path %>
<%end%>
</div>

app/views/krs/show.html.erb
<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item"><a href="/teams/<%=@team.id%>/okrs">Equipe: <em><%=@team.title%></em></a></li>
    <li class="breadcrumb-item"><a href="/teams/<%=@team.id%>/okrs/<%=@okr.id%>/krs">OKR: <em><%=@okr.title%></em></a></li>
    <li class="breadcrumb-item active"><strong>KR: <em><%=@kr.title%></em></strong></li>
  </ol>
</div>



<div class="row">
	<div class="container-fluid">		
		<div class="col-md-12">
			<div class="col-md-2">			
			</div>
				<div class="col-md-8">
					<div class="jumbotron well">
						<h1><%= @kr.title %></h1>
						<p><strong>How to score: </strong><em> <%=simple_format(@kr.howtoscore) %></em></p>												
						<p><strong>Progesso do KR: <%= @kr.progress %>%</strong></p>
						<hr>
						<div align="center">
						<%if current_user.editor %>
						<%= link_to 'Editar', edit_team_okr_kr_path(@team, @okr, @kr), class: "btn btn-primary" %> 
						<%end%>
						<%= link_to 'Voltar', team_okr_krs_path, class: "btn btn-primary" %>
						</div>						
					</div>
				</div>
			<div class="col-md-2">			
			</div>
		</div>
	</div>
</div>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Inkflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>



<style>
.footer
{
  height: 19px;
  position: absolute;
  left: 0;
  right: 0;
  bottom: 0;
  padding: 0;
  position: fixed;
}
.navbar-brand{
  padding-top: 5px;
  padding-bottom: 5px;
}

.dropdown {
  padding-right: 15px;
}
a {
  font-size: 20px;
}
</style>

  </head>

  <!--<body style="background-color:#f2f2f2">-->

  <font style = "font-family:verdana", color = 'purple'>




  <div class="row">
    <div class="col-md-12">
      <nav class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="navbar-header">

          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
             <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <%= image_tag("logo/logo.png", width: "100px", height: "40px") %>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="/presentation/index">Organograma</a>
            </li>
            <li>
              <a href="/teams">Equipes</a>
            </li>
            <li>
              <a href="/contact/index">Contato</a>
            </li>
            <li>
              <a href="/tutorial/index">Tutorial</a>
            </li>


          </ul>
          <%if user_signed_in?%>
          <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">

                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%if current_user.username.empty?%>
                <%=current_user.email%>
                <%else%>
                <%= current_user.username %>
                <%end%>
                <strong class="caret"></strong></a>


              <ul class="dropdown-menu">


                <%if current_user.admin %>
                <li>
                  <%= link_to 'Admin', rails_admin_path%>
                <li>
                <%end%>
                <li>
                  <%= link_to 'Editar', edit_user_registration_path, method: :get %>
                </li>
                <li class="divider">
                </li>
                <li>
                  <%= link_to 'Sair', destroy_user_session_path, method: :delete, data: { confirm: 'Tem certeza?' } %>
                </li>
              </ul>
            </li>
          <%end%>
          </ul>
        </div>
      </nav>
    </div>
  </div>





    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>


      </div>
      </div>


        <div class="footer" align="center">
            <p>&copy; Inkflow 2016, All rights reserved</p>
        </div>




  </body>
</html>

app/views/okrs/index.html.erb
<style>

th {
    text-align: center;
    background-color: purple;
    color: white;
    font-size: 20px;
}

td{
    background-color: white;
    text-align: center;
    font-size: 15px;
    color: black;
}
.percokr{
  width: 10%;
}
.nameokr{
  width: 20%;
}
.opcoesokr{
  width: 20%;
}
.progress {
  position: relative;

}
.progress span {
  position: absolute;
  display: block;
  width: 100%;
  color:purple;
}

</style>
<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item active"><strong>Equipe: <em><%=@team.title%></em></strong></li>
  </ol>
</div>


<div class="row">
  <div class="col-md-12">
    <div class="col-md-5">
    </div>
      <div class="col-md-1" align="center">
        <h5>Criar OKR</h5>
        <%= button_to new_team_okr_path(@team), method: :get, class: "btn btn-primary", title:"Criar OKR" do %>
        <span class="glyphicon glyphicon-plus"></span>
        <%end%>
      </div>
      <div class="col-md-1" align="center">
        <h5>Voltar</h5>
        <%= button_to teams_path, method: :get, class: "btn btn-info", title:"Equipes" do %>
        <span class="glyphicon glyphicon-arrow-left"></span>
        <%end%>
      </div>
    <div class="col-md-5">
    </div>
  </div>
</div>
<br>

<div class="container-fluid">
  <div class="row">

    <div class="col-md-12">
      <table class="table table-bordered">
        <thead>
          <tr>

            <th class="nameokr">
              OKR
            </th>
            <th>
              Descrição
            </th>
            <th class="percokr">
              Status
            </th>
            <th class="opcoesokr">
              Opções
            </th>

          </tr>
        </thead>
        <tbody>
          <% @team.okrs.each do |okr| %>
          <tr>
            <td>
              <strong><%= link_to okr.title, {:action => 'show', :id => okr.id}  %></strong>
            </td>
            <td>
              <%= simple_format(okr.description) %>
            </td>
            <td>

            <div class="progress" align="center" >
            <div class="progress-bar progress-bar-striped active" role="progressbar"  style="width: <%= progresso_okr(okr) %>%">
            <strong><span><%= progresso_okr(okr) %>%</span></strong>
            </td>
            <td>
              <%= link_to 'KR', team_okr_krs_path(@team, @okr), class: "btn btn-default"%>
              <%if current_user.editor%>
              <%= link_to 'Editar', {:action => 'edit', :id => okr.id}, class: "btn btn-default" %>
              <%= link_to 'Excluir', {:action => 'destroy', :id => okr.id}, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn btn-default" %>
              <%end%>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/okrs/show.html.erb
<div align="center">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/teams">Equipes</a></li>
    <li class="breadcrumb-item "><a href="/teams/<%=@team.id%>/okrs">Equipe: <em><%=@team.title%></em></a></li>
    <li class="breadcrumb-item active"><strong>OKR: <em><%=@okr.title%></em></strong></li>
  </ol>
</div>


<div class="container-fluid">
	<div class="row">		
		<div class="col-md-12">
			<div class="col-md-2">
			</div>
				<div class="col-md-8">
					<div class="jumbotron well">
						<h1><%= @okr.title %></h1>
						<p><strong>Descrição:</strong><em> <%=simple_format(@okr.description) %></em></p>							
						<p><strong>Progresso do OKR: <%= progresso_okr(@okr) %>%</strong></p>
						<hr>
						<div align="center">
						<%= link_to 'Mostrar KR', team_okr_krs_path(@team, @okr), class: "btn btn-primary" %>
						<%if current_user.editor %>
						<%= link_to 'Editar', edit_team_okr_path(@team, @okr), class: "btn btn-primary" %>
						<%end%>
						<%= link_to 'Voltar', team_okrs_path, class: "btn btn-primary" %>
						</div>
					</div>
				</div>
			<div class="col-md-2">
			</div>
		</div>
	</div>
</div>